FROM node:16-alpine3.11

RUN apk add git \
    && git clone https://github.com/Licege/serverNodeTX.git \
    && cd serverNodeTX \
WORKDIR /var/www/app

EXPOSE 9092

CMD env ${cat env} DEFAULT_EXECUTION_MODE="authorization" node index.js